.PHONY: all
all:
	$(MAKE) -C samd21a
	$(MAKE) -C samd21b
	$(MAKE) -C samd21c
	$(MAKE) -C samd21d
	$(MAKE) -C samd21l

.PHONY: clean
clean:
	$(MAKE) -C samd21a $@
	$(MAKE) -C samd21b $@
	$(MAKE) -C samd21c $@
	$(MAKE) -C samd21d $@
	$(MAKE) -C samd21l $@
